site_name: ScreamingBedWars
site_url: http://localhost:8000

theme:
  name: material
  custom_dir: ./overrides
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    # - navigation.tabs
  palette:
    - scheme: slate
      primary: teal
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: teal
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ScreamingSandals
    - icon: fontawesome/brands/discord
      link: https://screamingsandals.org/discord
  version:
    provider: mike
    default: latest

copyright: Copyright &copy; 2021 ScreamingSandals

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true

edit_uri: ""
repo_url: https://github.com/ScreamingSandals/BedWars
repo_name: ScreamingSandals/BedWars

plugins:
  - git-revision-date:
      enabled_if_env: CI
  - search

nav:
  - Home: index.md
  - Arena creation: arena.md
  - Configuration: config.md
  - Upgrades: upgrades.md
  - Placeholder API: placeholderapi.md
  - Troubleshooting and FAQ: troubleshooting.md
  - API: api.md