name: Bug report
about: Create a report to help us improve this project
title: '[Bug]: '
labels: ['bug', 'needs triage']
assignees: ''
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! Please follow the description of each individual input field.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: bw-dump
    attributes:
      label: BedWars dump (can be obtained via `/bw dump`)
      description: 'Please provide us with a link to the dump file. If you cannot obtain the dump, skip this field.'
    validations:
      required: false
  - type: textarea
    id: console-logs
    attributes:
      label: 'Console log'
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: 'Additional information'
      description: 'Here you can write any additional information which you think may help us. If you have not provided us with the dump, please give us here the following information: server and plugin version, configuration files (config.yml and shop.yml), installed plugins and additionaly arena files, if only specific arenas are affected.'
    validations:
      required: false
